### ISSUE TITLE
Run healthchecks in parallel

### ISSUE THREAD

**Issue by NatMarchand** [aspnet/Extensions#1009]
Hi there,
I would like to suggest running healthchecks in parallel.
We currently have multiple checks on dependencies (4-5) which can take around 100-200ms and in the end the whole healtcheck request can take up to a second or more which can cause timeouts upstream.
If it's just parallelizing the checks I'll be glad to make the PR. If there's a gotcha that I missed, please tell me in order to take it in account.
Thanks a lot !

**Comment by rynowak** [comment]
Hi @NatMarchand we would gladly accept a PR for this. 

You can find some similar logic inside [here](https://github.com/aspnet/Extensions/blob/master/src/HealthChecks/HealthChecks/src/HealthCheckPublisherHostedService.cs#L150) to what you will need. 

The one obvious gotcha here is that you will need to wait for all of the tasks to complete to create the results dictionary since dictionary isn't thread-safe.

@glennc - do you think it's worth adding an option or should we make this the default? This is something we considered from the beginning but I don't want to break people even if they are doing something we don't recommend.

**Comment by rynowak** [comment]
Done! Thanks @NatMarchand
