### ISSUE TITLE
[Question] Is it normal to depend on these packages in simple open source .NET project?

### ISSUE THREAD

**Issue by mifopen** [aspnet/Extensions#1112]
For example, I have a NuGet package project with HTTP client for some public API. Also, I want to assert some HTTP headers but only in debug/development mode. I cannot use `#if DEBUG` cause I want to distribute the library as a NuGet package that assembled with Release configuration. Is it normal to use `Microsoft.Extensions.Hosting.IHostingEnvironment` for such task? I do not want to frighten my package's users with dependencies that will discourage them.

**Comment by gfoidl** [comment]
> want to assert some HTTP headers but only in debug/development mode

You could provide a "switch" that enables these assertions to the users of your package. Either as argument, property, whatever -- default is no assertions, when the switch is enabled the assertions will be done. So in essence move the choice of debug / development one level up, to avoid the dependency to `IHostingEnvironment`. 
Disadvantage is that you need to document this.

**Comment by mifopen** [comment]
Yes, I could provide some parametrization and it seems to me that it is a good choice for that particular case.
But what about common sense of Microsoft.Extensions.* packages. Especialy *.Abstractions ones. My first opinion about them was that it is normal to provide Use/Add* IServiceCollection’s extensions, to provide IOption implementation for typed configuration for package and of course to use IHostingEnvironment. All of this looks like convenient building blocks for some incapsulation.
But then I thought that users could not use those standard things and it could be a little weird for them to see all those deps.
I saw additional packages for some packages (usually with *.AspNetCore suffix) that add this functionality as optional. What do you think about it? Should all package developers use this pattern?

**Comment by rynowak** [comment]
> Is it normal to use `Microsoft.Extensions.Hosting.IHostingEnvironment` for such task? I do not want to frighten my package's users with dependencies that will discourage them

I think it could be a good choice or maybe a weird choice depending on your project's goals and usage. 

---

The things that are `Microsoft.Extensions` are reusable components that solve common concerns for productionized server/cloud applications. Some things are more general:
- DI
- Logging
- Configuration
- Options

Some things are more specific:
- HTTP client factory
- Health checks

Hosting (`Microsoft.Extensions.Hosting`) is an app-model that ties all of these things together. If you're using Hosting in an application - it's because you want to have a solution for DI/Logging/Configuration. 

The major concern btw that's handled by Hosting is to give your application a lifecycle (start+stop). Another one is to tie the concept of background services (`IHostedService`) to the application's lifetime, and make it easy to manage.

----

So I guess I'll ask the question back at you - does this sound like a good fit for your goals and your library's users? 

If your question is limited is to "how should I provide some way for your users to configure an option for my library" it doesn't seem right *to me* to pull in all of the `Microsoft.Extensions` dependencies. Keep in mind also that we don't tie much functionality in asp.net core to the hosting environment - we leave that to the application developer to decide.

**Comment by mifopen** [comment]
@rynowak Thank you for your answer. I think I get your ideas. I will not make any particular assumptions about how my package's users will do things. It is normal to make it possible to set the library up without additional dependencies using c# only.
