### ISSUE TITLE
Add .pdb files to DI.Spec.Tests nuget

### ISSUE THREAD

**Issue by smalleythedave** [aspnet/Extensions#1282]
The published nuget for DI.Spec.Tests does not contain .pdb files. This means the tests cannot be debugged with Sourcelink.

I recently wrote an adapter for a container with the explicit goal of passing all the specification tests. When the tests fail, being able to debug them is essential to identify the problems. Of course, I was able to clone the tests and build them locally for debugging, but I think using Sourcelink would be better.

I don't think there is a use case for the tests (outside of the project itself) other than writing and testing other implementations/adapters, so debugging is always going to be necessary.

Dave

**Comment by Eilon** [comment]
Hi @smalleythedave we don't typically embed PDBs in the NUPKGs because it increases the size of the file for most people even though they don't need it. However, sourcelink should be enabled for all packages and I think the PDBs are on the public symbol servers.

Can you show what error(s) you got while trying to step into the code, and what debugger settings you are using?

**Comment by smalleythedave** [comment]
Hi Eilon,

You are quite right. I had enabled Sourcelink but not the Microsoft symbol servers.  After doing this the source gets downloaded and I can easily step into and inspect it. I guess including the pdb in the nuget is for libraries without a symbol server.

Thanks, Dave

**Comment by Eilon** [comment]
Glad you got it working! Closing this issue.
