### ISSUE TITLE
IMemoryCache needs a Clear method

### ISSUE THREAD

**Issue by jjxtra** [aspnet/Extensions#1305]
The amount of hacks online to try and clear IMemoryCache is disturbing. Please add a Clear method that will clear the inner EntriesCollection. Using Compact(0.0) does nothing.

Right now I have to resort to this hack:
```
PropertyInfo prop = cache.GetType().GetProperty("EntriesCollection", BindingFlags.Instance | BindingFlags.GetProperty | BindingFlags.NonPublic | BindingFlags.Public);
object innerCache = prop.GetValue(cache);
MethodInfo clearMethod = innerCache.GetType().GetMethod("Clear", BindingFlags.Instance | BindingFlags.Public);
clearMethod.Invoke(innerCache, null);
```

**Comment by JunTaoLuo** [comment]
Hmm, IMemoryCache  can be used as a shared component in DI. Though we don't recommend this since it's hard to control what goes in the cache and how it can be shared fairly among components, it's still a supported scenario. In a shared scenario, I'm not sure it'll be a good idea for one component to clear the cache for everyone else.

But there's room for improvements here and we'll consider potential ways to address this, though I doubt we'll be adding an explicit Clear method.

**Comment by jjxtra** [comment]
For unit testing it's very important to be able to clear in order to force any caching on the controller side to return fresh results. Otherwise there has to be a way to evict individual cache items which wasn't immediately obvious to me how to do that.

**Comment by JunTaoLuo** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.icacheentry.expirationtokens?view=aspnetcore-2.2

**Comment by jjxtra** [comment]
Looks like that works, however it requires a bit more setup in the unit tests since each and every cache item now needs a token.

Why does Compact(0.0) not clear the memory cache?

**Comment by JunTaoLuo** [comment]
Oh I misread what you were calling. You should call Compact(100) to remove all entries. https://github.com/aspnet/Extensions/blob/master/src/Caching/Memory/src/MemoryCache.cs#L382

**Comment by jjxtra** [comment]
That works, I had it backwards, ok made an extension Clear method with it, works. Yea!

**Comment by JunTaoLuo** [comment]
FYI, compact doesn't guarantee that the cache is cleared. Items marked with `CacheItemPriority.NeverRemove` will not be removed during compaction. Hence why I thought you were asking for a Clear method, which we were unsure if we'd want to implement. But glad your problem was solvable with the current APIs.

**Comment by jjxtra** [comment]
No worries. I don't use that attribute. If I did, I would be forced back to the reflection hack, but so far it has not been necessary. Perhaps a second overload of the Compact that specifies a max priority to remove?
