### ISSUE TITLE
How to register File providers for Razor in ASP.NET Core 3.0 ?

### ISSUE THREAD

**Issue by VBAndCs** [aspnet/Extensions#1325]
In ASP.NET Core, We used:
```
     services.Configure<RazorViewEngineOptions>(opts =>  
         opts.FileProviders.Add( new myFileProvider() ) 
     ); 
```

But this gives an error in ASP.NET Core 3.0 Preview, saying that there is no FileProviders property in RazorViewEngineOptions !
So, how this can be done today?

**Comment by VBAndCs** [comment]
Got it:
In ASP.NET Core 3.0, it is done using MvcRazorRuntimeCompilationOptions (needs to reference Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation:
```
     services.Configure<MvcRazorRuntimeCompilationOptions>(opts =>  
         opts.FileProviders.Add( new myFileProvider() ) 
     ); 
```

Thanks.

**Comment by DiegoStefanon** [comment]
Ok but it's not working !!

**Comment by rynowak** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
