### ISSUE TITLE
Confusing: Why are an extension like Configuration under ASP?

### ISSUE THREAD

**Issue by Bartolomeus-649** [aspnet/Extensions#1355]
It's kind of confusing when you se a super generic feature like Configuration, not logically and hierarchy belonging to the base .NET Core, and instead it's here, under ASP.NET.
What's the logic behind it?  

How do we as developers and partners to Microsoft know what it means when, for example,  Configuration is stuck under Asp.NET, is it only intended for Asp.Net? Will I have issues if I use it in a console app?  Perhaps it works in a console app now but since it's not intended to be used there, it will not work in a future version?

Also, there's no real documentation that I've found anywhere, that clarify and make it easy for developers and partners to understand which packages are available, where they are, what their intended use is, any limitations, prerequisites or dependencies for using them, when to use them and perhaps even more important, when not to use them.

Is this really what we as developers and partners using .NET Framework and .NET Core should spend our time on?

**Comment by kierenj** [comment]
It seems to me that the `dotnet` organisation is language-platform-oriented, and `aspnet` is application-framework-oriented (also having EF Core, etc).  Clearly EF Core is usable outside of ASP.NET Core too.

That said, `winforms` is under `dotnet`.. maybe because it's just too contradictory to have a desktop framework under and org which is named for a web framework.  Yeah, it definitely is a bit weird to me too.

However, I don't think there's a reason to assume at any point that any package is unusable or unsuitable for any particular use case unless it's implicit in the name.  I've not come across anything like that before - the package name and NuGet profile is surely more important and informative that the source code's GitHub organisation's name?

**Comment by gfoidl** [comment]
It's historic. ASP.Net Core needed some way of configuration (webservers, etc.), hence they came up with the config-package. That this package is usable outside of ASP.Net Core is nice to have.

> Will I have issues if I use it in a console app? Perhaps it works in a console app now but since it's not intended to be used there

(Right now) in .NET Core every app is a console app. ASP.Net Core web apps start as console apps, so (basically) there is no difference to other console apps.

> there's no real documentation

[Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration). If there is something unclear, missing, etc. feel free to add feedback / open an issue for this.

**Comment by rynowak** [comment]
Thanks @kierenj and @gfoidl - I'm not going to talk in too much detail about how our org chart is divided 😆. 

The best answer that I can give is that we intend for the `Microsoft.Extensions` libraries to be used by anyone who wants, for whatever they want. These are netstandard libraries that ship as packages, and suitable for building any kind of application.

I think a more important distinction is in how libraries ship, change and version rather than who built them. There's a very high overhead for putting something in the BCL compared with releasing a package. There is a bit of a historical element to this because we created these libraries before the shape of current .NET Core was really defined.

> (Right now) in .NET Core every app is a console app. ASP.Net Core web apps start as console apps, so (basically) there is no difference to other console apps.

This 💯 %

> However, I don't think there's a reason to assume at any point that any package is unusable or unsuitable for any particular use case unless it's implicit in the name. I've not come across anything like that before - the package name and NuGet profile is surely more important and informative that the source code's GitHub organisation's name?

I also super agree.

We're also doing some work to clear up what our documentation says about this libraries. We haven't done as much as we can make it clear we intend for them to be used in a variety of scenarios.

**Comment by Bartolomeus-649** [comment]
It is confusing, and the configuration in extension in ASP.NET was just an example.

Take these very simple and essential questions every developer and architect need to be able to answer, would you say it's an easy and straightforward process to figure these things out?

1. What is the method someone should use to figure out where to read about .NET Core to know what the different types of applications that can be made, and which features, packages, extensions and so on that's available from Microsoft for each of the different application types?

2. What method should be used to find the reference documentation for each "item" from point one (1)?

3. What method should be used to make sure that when you read documentation on one thing, you are not missing out on something really essential, which is documented somewhere else?

4. What method should be used to make sure that you use application types, features, packages, extensions and so on, in the way they are intended to be used, and in the way that ensures that it will work as intended in future versions?

5. What is the method to be used to make sure that if you find an application type feature, package, extension or something like that from Microsoft, that it is supported, that it will be around and Microsoft will continue develop and evolve it? 

Keep in mind things like Xamarin and PowerShell and such, which seem to live in part in a parallel world, but still release .NET Core modules, libraries and such...For example, UrhoSharp (https://docs.microsoft.com/en-us/xamarin/graphics-games/urhosharp/ , https://developer.xamarin.com/api/root/Urho/), it's in the official .NET documentation under Xamarin and gaming (but not for some reason in the gaming section of .NET), it looks official and supported, right?  It is delivered as a portable class library and supports .NET Standard 2.0 (and here I thought .NET Standard was a replacement of the PCL...)

**Comment by Bartolomeus-649** [comment]
just boring and uninteresting, or perhaps not relevant and important?
