### ISSUE TITLE
Add the ability to use modules (Similar to Ninject Modules)

### ISSUE THREAD

**Issue by f135ta** [aspnet/Extensions#1734]
Currently, all the registrations for services take place in a single ConfigureServices method. This is fine for small projects, but when your solutions grows to include many projects; it would be useful to split out these registrations into a seperate class contained within those projects. In a similar way to Ninject modules.

Creating a "Plugin" class would allow registrations to be made within the seperate projects to keep them clean/tidy. These plugins can be added into the ConfigureServices method to bring in those registrations.

You can use Ninject, but it would be nice to have this relatively small feature included as part of the main core solution.

**Comment by epignosisx** [comment]
The ASP.NET has been following the pattern of having an extension method on IServiceCollection from the libraries that want to participate in DI. See this example:

https://github.com/aspnet/Extensions/blob/master/src/Options/Options/src/OptionsServiceCollectionExtensions.cs

You can do the same from your library.

**Comment by f135ta** [comment]
That approach is fine if you’re directly referencing the other projects.. It gets a little more tricky if you’re trying to do some sort of autodiscovery and loading of DLLs

**Comment by anurse** [comment]
We don't have plans to add this kind of support directly to our DI container. Auto-discovery is a deceptively tricky feature. We think it's better to let the other containers provide this kind additional functionality since we keep our DI container limited to what is essential to the framework. You could certainly build logic in to your own `ConfigureServices` to scan for assemblies. It could also make for an interesting helper library for others to use.

**Comment by f135ta** [comment]
Thanks for the reply and clarification
