### ISSUE TITLE
Use an empty constructor in ActivatorUtilities.CreateInstance if none matches parameters

### ISSUE THREAD

**Issue by albertopaz-mt** [aspnet/Extensions#1806]
### Is your feature request related to a problem? Please describe.
Although it may be an antipattern, some projects use service providers to resolve dependencies. I had a project where two constructors existed in a class, one with arguments and another one without arguments. The empty constructor would use the service locator to provide dependencies to the other one.

```
public class Foo
{
   private readonly IDependency _dependency;

   public Foo(IDependency dependency)
   {
      _dependency = dependency;
   }

   public Foo() : this(ServiceLocator.GetService<IDependency>())
   {
   }
}
```

Some external libraries like Hangfire seem to use ActivatorUtilities.CreateInstance to create instances of custom types, with their custom service provider. In this case, _IDependency _ won't be registered on Hangfire's service provider, but it will registered on ServiceLocator. 

In the case above, _CreateInstance_ will find 0 argument matches for both constructors, so it will use the first one and try to resolve IDependency from the service provider passed by Hangfire, throwing an exception.

### Describe the solution you'd like
Use the first _empty_ constructor if all the constructors have 0 argument matches.

### Describe alternatives you've considered
Tag empty constructors with _ActivatorUtilitiesConstructorAttribute_.

### Additional context
N/A

**Comment by anurse** [comment]
One option is to apply the (somewhat obscure) [`ActivatorUtilitiesConstructorAttribute`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.activatorutilitiesconstructorattribute?view=aspnetcore-2.2) to the constructor in question which will cause `ActivatorUtilities` to prefer that constructor over all the others.

My understanding is that we very explicitly **don't** select constructors based on the availability of their arguments in the DI container. Instead, we take the "provided" arguments (the ones passed directly in to `ActivatorUtilities.CreateInstance`) and just find the **longest** constructor that can accept those. Then the remaining arguments are expected to be present. This behavior is designed to make things clear and deterministic and avoid issues like behavior changing because a DI service is removed from the container (meaning a different constructor would be selected). The attribute is there so that you can override that behavior. I may be wrong here though (cc @pakrym @davidfowl).

I would be interested in where we could improve the docs here. Are there places on docs.microsoft.com that you looked at and weren't able to find that information? Perhaps we could add it somewhere to help find the right resources.

**Comment by albertopaz-mt** [comment]
Hi @anurse, thanks a lot for your reply. I think the docs are quite clear, I did understood the behaviour you're explaining. What I think is that in this scenario:
- We don't provide any arguments to `ActivatorUtilities.CreateInstance`
- There's a constructor with no arguments and others with different arguments
Wouldn't it make sense to use the constructor with no arguments? I'd trust that constructor to be able to initialize the object state without needing any dependency.

**Comment by davidfowl** [comment]
That’s too big of a breaking change. It would need to be opt in or another method completely. 

Are you sure hangfire is using activator utilities? Seems like if you’re trying to solve this specific problem then you should file an issue on hang fire. We can’t change which constructor gets selected as that would impact so many other pieces of code that expect it to behave the way it does now
