### ISSUE TITLE
JSInterop failure to deserialize DOMString

### ISSUE THREAD

**Issue by drmathias** [aspnet/Extensions#1859]
### Describe the bug
When deserializing an object, a property with the type DOMString fails to deserialize to a C# string.

### To Reproduce

Invoke a C# method from JavaScript, passing an object which contains a DOMString property.

```javascript
window.addEventListener('keydown', (event) => passFunction(dotnetObjectInstance, event));

let passFunction = function (dotnetObjectInstance, event) {
    dotnetObjectInstance.invokeMethod('Invoke', event);
};
```

```csharp
public class KeyboardEvent {
    public string Type { get; set; }
    public string Key { get; set; }
    public bool IsTrusted { get; set; }
}

[JSInvokable]
public void Invoke(KeyboardEvent keyboardEvent)
{
    var type = keyboardEvent.Type; // null
    var key = keyboardEvent.Key; // null
    var isTrusted = keyboardEvent.IsTrusted; // true
}
```

### Expected behavior
The DOMString should deserialize to a C# string.

**Comment by SteveSandersonMS** [comment]
As far as I understand, this is as expected.

JS interop handles all parameters by JSON-serializing them. If in JavaScript you call `JSON.stringify` on a `KeyboardEvent`, the output is like this:

```
{"isTrusted":true}
```

That's all - it doesn't include the `key`, `code`, `type`, or anything else. So that's what the .NET side will receive.

If you want to pass more information to the .NET side, make sure it's in a form that JSON-serializes in the way you want.
