### ISSUE TITLE
update microsoft's implementation to use new stackexchange.redis binaries.

### ISSUE THREAD

**Issue by krishnasingh1818** [aspnet/Extensions#2313]
hi,

we are using msft redis cache nuget and i noted its using very old copy of stackexchange.redis.  
StackExchange team has made changes and bug fixes to its binary and currently at version 2.0.6 but msft implementation still using old copy.  

my request is to update msft extension to use latest stackexchangeredis nugets to benefit from fixes done by stackexchange teams.   

I tried to update msft cache to use latest stackexchange lib but started getting errors about some methods missing in newly published stackexchange libraries.

when can we get new version of msft redis cache library that uses latest version of stackexchange library ? pls advise.

thanks

**Comment by MisinformedDNA** [comment]
Also, [Microsoft.Extensions.Caching.Redis](https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis/2.2.0) (currently 2.2.0) depends on [StackExchange.Redis.StrongName](https://www.nuget.org/packages/StackExchange.Redis.StrongName/), which hasn't had a release since 2017. The next version of "Microsoft.Extensions.Caching.Redis" should replace that dependency with [StackExchange.Redis](https://www.nuget.org/packages/StackExchange.Redis/). (Which, BTW, is the same package that Microsoft's [RedisSessionStateProvider](https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/) and [RedisOutputCacheProvider](https://www.nuget.org/packages/Microsoft.Web.RedisOutputCacheProvider/) depend on.

**Comment by unicrus** [comment]
Because of the reference to StackExchange.Redis.StrongName, it's impossible to use the package Microsoft.Extensions.Caching.Redis with the package Microsoft.AspNetCore.DataProtection.StackExchangeRedis — they both contain the class StackExchange.Redis.ConnectionMultiplexer.

**Comment by MisinformedDNA** [comment]
@Pilchie Do you know if MS plans to tackle this in the near future? If we could get some kind of response from MS, maybe someone in the community could pick this up?

**Comment by anurse** [comment]
In order to support the new 2.x version of `StackExchange.Redis` we actually shipped **brand new packages** for all our Redis integrations in 2.2 and phased the old ones out in 3.0. See https://github.com/aspnet/Announcements/issues/322 for some details here.

You do need to change all your package references to the `.StackExchangeRedis` variant, otherwise you will get conflict issues like @unicrus observed. However, the APIs exposed by these packages remain almost exactly the same (instead of `.AddRedisCache` methods, you'll find `.AddStackExchangeRedisCache` methods, but otherwise the API is the same) so the upgrade should be straightforward.

We used a new package because the move from 1.x to 2.x is a *breaking change* (as @krishnasingh1818 observed above). Not only because there are breaking API changes in the StackExchange.Redis package, but because the package ID **changed** from StackExchange.Redis.StrongName to StackExchange.Redis.

Does this clear things up?

**Comment by MisinformedDNA** [comment]
Awesome. Thanks. Is there a way that we could "redirect" users from Microsoft.Extensions.Caching.Redis to Microsoft.Extensions.Caching.StackExchangeRedis? Like updating the description or release notes?

**Comment by anurse** [comment]
We may do something like that when the deprecation feature for NuGet lands: https://devblogs.microsoft.com/nuget/deprecating-packages-on-nuget-org/

**Comment by anurse** [comment]
Though I don't think we'd want to deprecate them, since 2.1 is supported for a few more years.

We could look at a description update to add a note like: "For .NET Core 3.0 apps, use NNN.StackExchangeRedis instead"

**Comment by krishnasingh1818** [comment]
> In order to support the new 2.x version of `StackExchange.Redis` we actually shipped **brand new packages** for all our Redis integrations in 2.2 and phased the old ones out in 3.0. See [aspnet/Announcements#322](https://github.com/aspnet/Announcements/issues/322) for some details here.
> 
> You do need to change all your package references to the `.StackExchangeRedis` variant, otherwise you will get conflict issues like @unicrus observed. However, the APIs exposed by these packages remain almost exactly the same (instead of `.AddRedisCache` methods, you'll find `.AddStackExchangeRedisCache` methods, but otherwise the API is the same) so the upgrade should be straightforward.
> 
> We used a new package because the move from 1.x to 2.x is a _breaking change_ (as @krishnasingh1818 observed above). Not only because there are breaking API changes in the StackExchange.Redis package, but because the package ID **changed** from StackExchange.Redis.StrongName to StackExchange.Redis.
> 
> Does this clear things up?

I updated the new nuget and its working great. lot of error logs related to cache taking more than a second (which we had put) is not showing up. thank you !

**Comment by anurse** [comment]
Closing as it sounds like the version confusion is cleared up.

> lot of error logs related to cache taking more than a second (which we had put) is not showing up.

@krishnasingh1818 if you're seeing an issue with the new package, please file a new bug for that.
