### ISSUE TITLE
Why does the Extensions packages target .NETCoreApp 3.0 (instead of .NETStandard 2.1)?

### ISSUE THREAD

**Issue by 304NotModified** [aspnet/Extensions#2445]
Maybe I missed it with the release notes,

but why does the Extensions packages target .NETCoreApp 3.0?

e.g.

Microsoft.Extensions.Configuration.Abstractions

![image](https://user-images.githubusercontent.com/5808377/66086405-477f4180-e574-11e9-9f22-7c6f3c5f4103.png)

- Why doesn't it target .NETStandard 2.1 instead of  .NETCoreApp 3.0?
- Why was .NETStandard 2.0 not enough? (.NET Core 3 could use .NET standard 2)?
- Most important, as a library owner that depends on Microsoft.Extensions.Configuration.Abstractions, should I also target .NETCoreApp 3.0 next to  .NETStandard 2.0? Is it recommend in some situations?

**Comment by michael-wolfenden** [comment]
> Most important, as a library owner that depends on Microsoft.Extensions.Configuration.Abstractions, should I also target .NETCoreApp 3.0 next to .NETStandard 2.0?

Just to add to this, there appears to be some confusion from library authors as to how to best consume these packages

- [Should a library explicitly target .NET Core 3?](https://stackoverflow.com/questions/57846163/should-a-library-explicitly-target-net-core-3)
- [Microsoft.Extensions.* version confusion](https://stackoverflow.com/questions/58193023/microsoft-extensions-version-confusion)

It would be nice to see some official guidance around consuming these packages as a library author.

**Comment by Pilchie** [comment]
@JunTaoLuo can you explain the reasoning here?

**Comment by Pilchie** [comment]
Tagging @DamianEdwards too

**Comment by 304NotModified** [comment]
> Just

Thanks! FYI the first stackoverflow question is also by me :angel:

**Comment by DamianEdwards** [comment]
Documentation for library authors is currently being developed. You can track progress at aspnet/AspNetCore.Docs#14309

In this case, I believe the Extensions packages target both TFMs due to the fact they are also shipped as part of the Microsoft.AspNetCore.App shared framework, which has special requirements regarding source buildaibility (the ability for 3rd part entities to successfully build the .NET Core SDK and runtimes for embedding in their product, e.g. Red Hat Enterprise Linux).

So for general library authors, the guidance is to target `netstandard2.0` at a minimum, and then only target further or other TFMs when and if the library needs to, e.g. because they require an API from that TFM or a related `FrameworkReference`, or they have a dependency on a package that uses another TFM, etc.

**Comment by JunTaoLuo** [comment]
What @DamianEdwards says is correct. We target netcoreapp3.0 in Extensions in order to support the build from source effort. Library authors don't have to do so if they don't need any new APIs in netcoreapp3.0
