### ISSUE TITLE
Symbols missing for microsoft.extensions.commandlineutils 1.1.1

### ISSUE THREAD

**Issue by IlyaBiryukov** [aspnet/Extensions#2499]
Our VS payload depends on `microsoft.extensions.commandlineutils` 1.1.1.
When we do insertion into VS, it complains that it cannot find symbols for microsoft.extensions.commandlineutils.dll, see [VS #958010](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958010/)
The PDB signature hash it's looking for is `D1A06F78-7E8D-400B-ACA1-15CC3DA0A798`

**Comment by Pilchie** [comment]
@aspnet/build anyone have any ideas?  @IlyaBiryukov I'm going to guess that you should be on a MUCH newer version as 1.1 has been out of support for a while know.

**Comment by dougbu** [comment]
We no longer support Microsoft.Extensions.CommandLineUtils. We have a similar shared source package but only for use within ASP.NET Core projects.

@IlyaBiryukov what "VS payload" are you talking about?

**Comment by IlyaBiryukov** [comment]
We use `Microsoft.Extension.CommandLineUtils` in our Live Share extension, and when we insert it into VS (e.g. [This insertion](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/206605?_a=overview)), VS complains about missing symbols.

What newer version would you recommend? The one you still support that is.

**Comment by dougbu** [comment]
I don't recommend using either `Microsoft.Extension.CommandLineUtils` or the newer `Microsoft.Extension.CommandLineUtils.Sources` outside ASP.NET Core repos. I'm surprised you took a dependency on the `Microsoft.Extension.CommandLineUtils` package.

`Microsoft.Extension.CommandLineUtils.Sources` is still in use for our repos but it's a shared source package, meaning you'll need to _disable_ VS insertions and compile against the new package instead.

**Comment by IlyaBiryukov** [comment]
So, your recommendation would be to switch to `Microsoft.Extension.CommandLineUtils.Source`? I don't see it on NuGet.org.

We cannot *disable* our insertions into VS. We ship with VS, and our package is enabled by default in several setup workflows. 

The NuGet package `Microsoft.Extensions.CommandLineUtils` is public on [NuGet.org](https://www.nuget.org/packages/Microsoft.Extensions.CommandLineUtils/) and has 6K downloads per day and 2M total downloads for 1.1.1. Widely used by community it looks like. Are you sure it's discontinued?

**Comment by dougbu** [comment]
> Are you sure it's discontinued?

Yup. We last updated `Microsoft.Extensions.CommandLineUtiils` more than 2 years ago.

> We cannot _disable_ our insertions into VS

Sorry, I wasn't clear. I was talking about not inserting just `Microsoft.Extensions.CommandLineUtiils` while building your code against `Microsoft.Extensions.CommandLineUtiils.Sources`.

Mid-term I'd prefer you transition to 

> I don't see it on NuGet.org.

It's available in a couple of feeds, including 
- https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-transport/nuget/v3/index.json
- https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet3.1-transport/nuget/v3/index.json
- https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet3-transport/nuget/v3/index.json

----
Overall this short-term change would give you symbols and allow your code to remain unchanged (modulo whatever we've fixed in the .Sources package). But, I recommend moving to another option mid-term because we're talking about an implementation detail of ASP.NET Core that isn't supported outside our small group.

@Pilchie please jump in to confirm, deny or change what I'm saying here. (We certainly can do things differently going forward.)

**Comment by pranavkm** [comment]
AspNetCore did not publish symbols to feeds as part of the 1.1 release, but I might be able to wrangle the symbol from the build drop share. Taking this offline. For all other users, https://github.com/aspnet/Extensions/issues/257 has some suggestions for alternative command line parsers to use.

**Comment by jmarolf** [comment]
Just want to chime in that there are still no symbols uploaded for this nuget package. We were also bitten by this while inserting into VS. @pranavkm would you consider de-listing the package from nuget if no one is supposed to use it?
