### ISSUE TITLE
ActivatorUtilities.CreateInstance cares only length of constructor parameters but not availability

### ISSUE THREAD

**Issue by deerchao** [aspnet/Extensions#427]
In the constructor matching process of method ActivatorUtilities.CreateInstance(IServiceProvider, Type, params object[]), parameter's availability is not considered, which should be.

To demonstrate the possible outcome of this behavior, let's see a simple middleware and its usage:

    // In Startup.cs
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddOptions();
        services.Configure<ServerApiConfig>(Configuration.GetSection("serverapi"));
        services.AddSingleton<ServerApiMiddleware>();
    }

    // In a library project
    public class ServerApiConfig
    {
        public int SomeThingToConfig {get;set;}
    }

    public class ServerApiMiddleware
    {
        private readonly RequestDelegate _next;
        private readonly ServerApiConfig _config;

        // We want to keep this constructor because we don't want to limit consumers' choices, maybe they like providing an instance instead of using options pattern
        public ServerApiMiddleware(RequestDelegate next, ServerApiConfig config)
        {
            _next = next;
            _config = config;
        }
        
        // If this constructor appears first in source code, then everything works.
        // However if this appears after the other constructor, we would have an exception:
        // InvalidOperationException: Unable to resolve service for type 'ServerApiConfig' while attempting to activate 'ServerApiMiddleware'.
        public ServerApiMiddleware(RequestDelegate next, IOptions<ServerApiConfig> config)
            : this(next, config.Value)
        {
        }

        public async Task InvokeAsync(HttpContext context, IServerAppProvider appProvider)
        {
            throw new NotImplementedException();
        }
    }

We would expect that the physical ordering of two constructors in source code does not affect how we use this middleware, but that's not the case. `ActivatorUtilities.CreateInstance`(called by `UseMiddlewareExtensions.UseMiddleware`) uses whichever constructor that comes first since both have two parameters, so the ordering in source code decides if it's working or not.

I see two possible improvements:
1. Add an method `IsServiceAvailable(Type)` to `IServiceProvider `, and `ActivatorUtilities` takes the availability of parameters into account
2. `ActivatorUtilities` does not pick *one* bestMatcher, but *several* bestMatchers depending parameters length, and try to invoke these constructors, return the first result that succeeds.

**Comment by poke** [comment]
Since you are not passing any manual arguments to `ActivatorUtilities.CreateInstance`, *all* constructors will match equally well as far as `ActivatorUtilities` is concerned. Because it simply matches based on how many of the passed arguments it can match for a constructor. If there are multiple matches with equally well matching arguments, then it will simply choose the first constructor of those.

You can affect that behavior by decorating one of your constructors with the `[ActivatorUtilitiesConstructor]` attribute. That will make `ActivatorUtilities.CreateInstance` always use that constructor.

Usually, if you don’t have any arguments to pass, you shouldn’t use `ActivatorUtilities` at all but just resolve the type directly from the `ServiceProvider` (which already has a smarter way to take into account which constructor arguments can be resolved). Of course, this being in the `UseMiddlewareExtensions` makes this suggestion a bit difficult to follow.

- I don’t think a method to check if a type is available from a service provider is that practical. The knowledge is currently also hidden quite deep inside of the providers internals. And since this would have to be available for all `IServiceProvider` implementations, we couldn’t do this without all the other providers also doing this. So that likely won’t happen.
- If you *do* pass arguments to `ActivatorUtilities.CreateInstance` or `UseMiddleware<T>`, I would still consider it correct or at least acceptable that it will pick the first best matching constructor even if that means that a dependency cannot be resolved. This is already an edge case and you should probably make sure that you don’t have too many overloaded constructors anyway.
- Maybe we should add an optimization to `ActivatorUtilities.CreateInstance` that will just forward to `IServiceProvider.GetService` when there were no arguments passed. But on the other hand that would require the type to be registered in the first place which the utilities currently do not require; and doing that would change the semantics since it would no longer be guaranteed that the exact type will be constructed or even that the type will be *constructed* (since it could be a singleton). – Difficult 😕

**Comment by deerchao** [comment]
Thanks, well explained, that makes sense, I guess it could be considered as options pattern(or how I use it)'s problem since IServiceProvider does not support resolving services with partial arguments provided, and ActivatorUtilities's behavior is well defined.
Meanwhile, UseMiddlewareExtensions is passing the RequestDelegate it built as the first argument, so if only IServiceProvider gives a little help on type availability, it would worked. Of course I understand this is unlikely to happen, so I'll just close this issue.
Thanks again.
