### ISSUE TITLE
Add a header propagation middleware and message handler

### ISSUE THREAD

**Issue by rynowak** [aspnet/Extensions#526]
We should consider providing an in-the-box solution for propagating headers from the current request to an outgoing http request.

This would consist of a middleware that can be configured to *stamp* certain headers on a feature of the current request. Then a message handler uses `IHttpContextAccessor` to grab the feature and apply the headers to outgoing requests. 

Maybe similar to:
https://github.com/stevejgordon/CorrelationId/tree/dev/src/CorrelationId from @stevejgordon or 
(sample @davidfowl made)

Also consider using `Activity`

**Comment by alefranz** [comment]
I'd like to help moving this forward. Would be creating a PR the best approach?
I plan to use @davidfowl gist with minor tweaks and a small addition.

Thanks

**Comment by Symbianx** [comment]
For people who step in this issue looking for a way to easily propagate the ISTIO tracing headers like I did, we created a library just for that, you can find it here: https://github.com/nosinovacao/istio-tracing-aspnetcore .

@alefranz it also may be a good starting point for your PR.

**Comment by alefranz** [comment]
@Symbianx I was actually waiting for a reply to submit a PR but I had already hacked some code. I've now submitted it, IT would be great if you can have a look and let me know if this cover your needs. I will try to have a look at that library tomorrow.

**Comment by acds** [comment]
I’ve been following this as a micro service developer, and really appreciate this is being looked at. 

My main use case is in terms of tracing and tracking but do also see value in propagating other headsets including and authentication tokens for end-to-end authentication between micros services.

It would also be useful to hook any header propagation middleware such that one can leverage the hook to push headers into properties in ones logging context in a central place (like a SeriLog enricher)

**Comment by antoinebj** [comment]
Is #1099 really viable with multithreading?

I'm currently using v2.2 with the need to propagate a header. However, I'm stuck with the old ASP.NET Web API 2, so instead of IHttpContextAccessor, I have to make do with HttpContext.Current. Obviously I ran into trouble the moment the HttpClient was being used from another thread (therefore with no associated HttpContext), because the delegating handler's SendAsync() was also running on that thread.
So I was curious to look at the implementation done here to see if I could get a solution that I could backport.

I read the IHttpContextAccessor is not thread safe, I'm assuming it has the same limitations whereby you cannot get the HttpContext if the code is not running on the request's thread.
If that is the case, I don't see where you avoid the same problem that I ran into.

Furthermore, the pooling of message handlers is great, but I'm wondering if the design isn't fundamentally flawed. Apparently it does not allow to get scoped information into the handler instance, and that creates all sorts of frustrations.
Honestly, the workaround described [here](https://github.com/aspnet/HttpClientFactory/issues/166#issuecomment-427257520) is very unpleasant and kind of feels like the HttpClientFactory library becomes pointless. I was planning to write custom AddTypedClient extension methods to replace the original ones, but the latter make use of a private `ReserveClient` method, which I'm not able to call. I don't want to pull a thread that leads me to rewriting a significant part of the library.

**Comment by rynowak** [comment]
This will be included in preview 6. https://github.com/aspnet/AspNetCore/pull/9793

Thanks @alefranz for doing 99% of the work for this!

**Comment by alefranz** [comment]
I've aslo published an unofficial backport to AspNetCore 2.1 and 2.2.
https://www.nuget.org/packages/HeaderPropagation/

I'll update it now with the latest changes.

**Comment by antoinebj** [comment]
@alefranz Thanks a lot. I understand now, the key to getting this to work across threads and through the asynchronous execution flow is to use AsyncLocal.

**Comment by acds** [comment]
@alefranz Nice!

Is there a standardized compatible with this library, to support a way to pick the current header values up, such that they could be injected into say the Serilog context via: 

```LogContext.PushProperty($"{headerName}", headerValue)```

with each scope/request being processed such that any logging pick up those header values (where `headerName` is known - and defined in the `services.AddHeaderPropagation` config)?
