### ISSUE TITLE
AddHostedService() registers service as Transient in the 2.1.1 apart from the 2.0

### ISSUE THREAD

**Issue by sguryev** [aspnet/Extensions#553]
Hello.

According to the documentation for the `2.0`
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.0#timed-background-tasks
We have to register services as Singleton
![image](https://user-images.githubusercontent.com/6978458/42641404-2becbc68-85fd-11e8-8280-6ddd81d33dda.png)

According to the documentation for the `2.1`
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1#timed-background-tasks
We should use the `AddHostedService` extension
![image](https://user-images.githubusercontent.com/6978458/42641477-4e506cb4-85fd-11e8-9937-c2958a9d435f.png)
which is Transient under the hood now: https://github.com/aspnet/Hosting/blob/master/src/Microsoft.Extensions.Hosting.Abstractions/ServiceCollectionHostedServiceExtensions.cs#L18

So my questions are: 
1. Can it be a problem and why have you changed the lifetime? 
2. What should I do If I have one more interface to reach the the service from the DI? Right now I'm doing the following:
Register custom interface as singleton:
`services.AddSingleton<ICandleSubscriptionHostedService, CandleSubscriptionHostedService>();`
Use the custom resolver for the `IHostedService` registration:
`services.AddSingleton<IHostedService, CandleSubscriptionHostedService>(provider => (CandleSubscriptionHostedService) provider.GetRequiredService<ICandleSubscriptionHostedService>());`
Both are Singletons so the second lifetime doesn't matter a lot actually.

Thank you!

**Comment by schmitch** [comment]
@davidfowl sorry to actually "hijack" such an old issue, but I have a question.

Currently I try to use the `IHostedService` to actually have a way to Start/Stop Services from a Razor Page. I mean I registered the Services I want to stop/start as a Singleton and I have a special class that is derived from IHostedService, i.e. `NamedHostedService` that also needs to set a Name Parameter so that when I get all NamedHostedServices, I know which one does what.

So is this a "good" use of IHostedService or shouldn't this be done, from all the Issue's it's unclear if such use cases are ok, I think the documentation should clear this up.

**Comment by kayjtea** [comment]
AddHostedService *should not* be a singleton. Please don't make this breaking change, or if you do, introduce an IHostedApi or some such.  The hosted service is just a service container -- the main reason to use it is because you need something running in the background with app life time. And in fact, BackgroundService is an IHostedService. You can use BackgroundService as a worker pool (by calling AddHostedService repeatedly), without having to deal with thread pools  at all, which is extremely nice. If you need an API just do like @davidfowl suggests and inject a singleton. If you need to use IHostedService as an API then you're going to have to deal with threading issues, and it's much easier to concentrate the thread-safe state in the injected singleton anyway.

Try this example: your app needs to collect and report statistics by sampling every 1 second and reporting every 5 minutes. If you design it the way @davidfowl suggests, the implementation just falls into place very neatly: you have a singleton thread-safe Statistics class that is injected every place where statistics need to collected, for example, in your controllers, and then you have two IHostedService: one to reset the statistics every second and another to report it every 5 minutes. Much cleaner than having the controllers invoke the hosted services directly.

**Comment by davidfowl** [comment]
Yea that’s not how it’s supposed to work, you should create your own abstraction for that. The hosted service is resolved once by the runtime and shouldn’t be resolved by your code. What did your logic look like before? You can really call AddHostedService once at startup so how does making it a singleton break your logic?

**Comment by jjxtra** [comment]
Is there a reason AddHostedService doesn't have overloads for an object and func creator?

**Comment by Tratcher** [comment]
Because it's a helper for what we expect is the most common scenario. If that doesn't suit you then use the DI methods directly.

**Comment by jjxtra** [comment]
Thanks for clarifying. That was very much not obvious to me, it took me a few days to find an example using AddSingleton with IHostedService. Please consider adding the two overloads in .NET 3.0.

**Comment by richardgavel** [comment]
One thing I'm not sure of, even with the transient registration is why, in certain cases, the IHostedService is being resolved from the DI container more than once by ASP.NET core. I understand if independent code is resolving an instance, more than one might be created. I'm running this in IIS, any chance app pool recycling could come into play?

**Comment by Tratcher** [comment]
@richardgavel yes, an app pool recycle would restart your app and re-resolve all DI services, regardless of transient or singleton.

**Comment by robertjak** [comment]
Workaround till .NET Core 3.0:
` services.AddSingleton<BackgroundWorkerService>();
  services.AddSingleton<IHostedService>(p => p.GetService<BackgroundWorkerService>());`

**Comment by aaronhudon-ts** [comment]
> Workaround to use IHostedService as API in .NET Core 2.1:
> 
> ```
> services.AddSingleton<BackgroundWorkerService>();
> services.AddSingleton<IHostedService>(p => p.GetService<BackgroundWorkerService>());
> ```
> 
> P.S.
> I also prefer concrete classes. _Entia non sunt multiplicanda sine necessitate :)_

Pages of comments, leads to this decent workaround.  Thanks @robertjak
