### ISSUE TITLE
Create opinionated meta package for extensions

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Extensions#597]
We'd like to create a meta package that contains a `Host.CreateDefaultBuilder` with a set of opinionated defaults. Thinking about this more I think we should keep the good name for the meta package **Microsoft.Extensions.Hosting** and make a new **Microsoft.Extensions.Hosting.Core** that contains what Hosting is today. 

cc @glennc @rynowak @Tratcher

**Comment by rynowak** [comment]
metapackage of shared framework :trollface:

**Comment by Tratcher** [comment]
I'm not convinced we actually need a new assembly/package in this case. It was required for WebHost because there was no other package that could pull in Hosting, servers, middleware, etc. In the generic host scenario it's only pulling in lower level components. E.g. these are the dependencies that might need to be added, none of which are onerous:
Microsoft.Extensions.Configuration.EnvironmentVariables
Microsoft.Extensions.Configuration.CommandLine
Microsoft.Extensions.Configuration.Json
Microsoft.Extensions.Configuration.UserSecrets
Microsoft.Extensions.Logging.Console
Microsoft.Extensions.Logging.Debug
Microsoft.Extensions.Logging.EventSource

Including Console and CommandLine makes sense as we already have a built in ConsoleLifetime. UserSecrets seems like the only very optional feature.

**Comment by davidfowl** [comment]
We'll need user secrets to be in by default as well so unless anyone has any objections. These packages will be added to the default Microsoft.Extensions.Hosting.
