### ISSUE TITLE
Unable to combine with Microsoft.AspNetCore.DataProtection.StackExchangeRedis

### ISSUE THREAD

**Issue by Vandersteen** [aspnet/Extensions#614]
### Describe the bug
When using Microsoft.Extensions.Caching.Redis and Microsoft.AspNetCore.DataProtection.StackExchangeRedis together you get an issue that ConnectionMultiplexer type exists twice.

Once in StackExchange.Redis & once in StackExchange.Redis.StrongName

**The type 'connectionmultiplexer' exists in both 'stackexchange.redis.strongname' ...**

### To Reproduce
1. Using version '2.1.2' of package 'Microsoft.Extensions.Caching.Redis'
2. Using version '2.2.0' of package 'Microsoft.AspNetCore.DataProtection.StackExchangeRedis'

```c#
var redis = StackExchange.Redis.ConnectionMultiplexer.Connect("localhost");
services.AddDataProtection()
              .PersistKeysToStackExchangeRedis(redis);
```

**Comment by davidfowl** [comment]
Yes this won’t work. Use https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis/2.2.0

**Comment by laskoviymishka** [comment]
Hi, Do you have any plans to fix it?
Actually it's quite a big issue for me. Since `Microsoft.Extensions.Caching.StackExchangeRedis` included in `Microsoft.AspNetCore.All` package and fetch `StackExchange.Redis.StrongName` 1.2.6 by strong name i'm unable to use redis in my application since `StackExchange.Redis.StrongName` is not support ipv6 network. The only way to break this hack an assembly of `StackExchange.Redis.StrongName` to add follow fix - https://github.com/StackExchange/StackExchange.Redis/pull/686/commits/300baed206f671f471bd3ffe01de1ae0e7437bda .
Any thoughts / plans to fix it?

**Comment by laskoviymishka** [comment]
Or at least upgrade to 2.x version -_-

**Comment by laskoviymishka** [comment]
Sorry for Inconvenience. But i refer redis package itself, not aspnet package. It reference to rather old 1.x version

**Comment by SeriousM** [comment]
> 
> 
> Sorry for Inconvenience. But i refer redis package itself, not aspnet package. It reference to rather old 1.x version (https://github.com/aspnet/Extensions/blob/master/eng/Baseline.Designer.props#L30)

That's right, I just found that the package `StackExchange.Redis.StrongName` was abandoned and only `StackExchange.Redis` is maintained.
https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes

The upside of this is that the later package `StackExchange.Redis` is strong named since 2.x!

@davidfowl is there any change that the package gets an update / nuget reference update?

**Comment by SeriousM** [comment]
Nevermind, `Microsoft.Extensions.Caching.StackExchangeRedis` is the update I asked for.

**Comment by anurse** [comment]
To clarify for folks here:

The existing package is staying on `StackExchange.Redis.StrongName`, a **new** package `Microsoft.Extensions.Caching.StackExchangeRedis` was introduced that references the new `StackExchange.Redis` package. The API is the same, with some minor namespace changes.

This was done because the `StackExchange.Redis` 2.0 release is a breaking change.

Closing as I don't think there's actionable work for us here now. Let us know if that changes!
