### ISSUE TITLE
Add support for syslog compatible priority numbers to our console logger.

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Extensions#647]
_From @mattiasw2 on September 25, 2018 6:11_

An important part of journalctl is priorities. The standard logger should do this, since this is the way you will run kestrel on Linux.

Add support for syslog compatible priority numbers to our console logger.

For more info, see https://github.com/aspnet/KestrelHttpServer/issues/2679

_Copied from original issue: aspnet/KestrelHttpServer#2955_

**Comment by ATLSAPI** [comment]
If this helps, I had the same issue and required the same functionality. I've tried that library and it converts the log levels to syslog and journalctl priority as expected. It also logs detailed exception/inner exception stack trace. This functionality will definitely be useful if it was integrated in as without this all logs came through as level 6 info in syslogs which is hardly helpful for configuring error alerts etc on nix hosted applications.

**Comment by anurse** [comment]
I think this discussion fits just fine in this issue. I'm not super familiar with how the console logger would interact with `journalctl` here. Do you have a reference doc I could look at?

This would certainly have to be either a) a different logger or b) a configuration on the existing logger, but in general we don't have a problem integrating functionality like this into the core if it will have very broad usage.

Is there any concern you have with using the existing library for this? I ask primarily because when setting priorities, if there's an existing library to do something we do take that into consideration (we can't do everything ;)).

**Comment by anurse** [comment]
I'll throw this on the backlog so that we can keep the discussion going.

**Comment by ATLSAPI** [comment]
Hi @anurse, thanks for responding to my comment. 

First a quick clarification, the library https://github.com/tmds/Tmds.Systemd correctly converts Microsoft.Extensions.Logging.LogLevel to syslog priority levels, but sends these logs structured to the systemd journal. Although structured logging to the journal was very useful especially when shipped and indexed with tools like Elasticsearch, Graylog, etc, that was really an added advantage.

The actual issue is that the ConsoleLogger when running on Linux, logs to syslog with incorrect priority numbers; basically all logs come through as level 6 - Information. This should really be fixed, to be honest, without an external library. In my situation, I didn't need Journal logging, even though the library was very good and came with added benefits. What I really needed was correct log levels/priority numbers to appear in syslogs and this is what should be looked at. 

Hope this helps

**Comment by anurse** [comment]
Can you clarify why the console logger is logging to syslog here? I'm not really familiar with systemd mechanics. My understanding is that syslog is a separate logging facility, not connected to the console. Is systemd scraping the console and parsing the log somehow?

Basically, I'm looking to understand what change we would need to make to improve this.

**Comment by tmds** [comment]
Now the console output looks like:
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/  
```
For systemd to pick up the priorities it needs to look like:
```
<prio>message
```
prio is a number:
```
           Numerical         Severity
             Code

              0       Emergency: system is unusable
              1       Alert: action must be taken immediately
              2       Critical: critical conditions
              3       Error: error conditions
              4       Warning: warning conditions
              5       Notice: normal but significant condition
              6       Informational: informational messages
              7       Debug: debug-level messages

              Table 2. Syslog Message Severities
```
We need to map `enum LogLevel` to these numbers, suggestion:
```
        Trace = 0,
-> 7 (Debug)
        Debug = 1,
-> 7 (Debug)
        Information = 2,
-> 6 (Informational)
        Warning = 3,
-> 4 (Warning)
        Error = 4,
-> 3 (Error)
        Critical = 5,
-> 2 (Critical)
        None = 6,
-> not mapped
```
And a way to change the ConsoleLogger to use this format, suggestion:
```cs
enum ConsoleLogFormat
{
    Default,
    Systemd
}
class ConsoleLoggerOptions
{
     ConsoleLogFormat Format { get; set; }
}
```
Note that the [actual syslog format](https://tools.ietf.org/html/rfc5424#section-6) is more elaborate:
```
      SYSLOG-MSG      = HEADER SP STRUCTURED-DATA [SP MSG]

      HEADER          = PRI VERSION SP TIMESTAMP SP HOSTNAME
                        SP APP-NAME SP PROCID SP MSGID
```
What we are talking about here is a simpler `<prio>message` format understood by systemd when reading the application standard out.

@glennc @davidfowl @anurse wdyt about the suggested API and mapping?

**Comment by anurse** [comment]
If it really is just about changing the format, I think it's reasonable to add this to the ConsoleLogger. Is there any situation where a user might want BOTH a syslog AND a regular console logger? Seems like that would be weird since the whole deal here is that you're piping the console to syslog somehow.

**Comment by tmds** [comment]
> If it really is just about changing the format, I think it's reasonable to add this to the ConsoleLogger

Yes, because both are writing to standard out.

> Is there any situation where a user might want BOTH a syslog AND a regular console logger? Seems like that would be weird since the whole deal here is that you're piping the console to syslog somehow.

Exactly.

**Comment by ATLSAPI** [comment]
> Can you clarify why the console logger is logging to syslog here? I'm not really familiar with systemd mechanics. My understanding is that syslog is a separate logging facility, not connected to the console. Is systemd scraping the console and parsing the log somehow?
> 
> Basically, I'm looking to understand what change we would need to make to improve this.

@anurse Apologies I haven't replied to this. We use supervisord to monitor the Kestrel processes and use Apache as a reverse proxy as recommended [https://docs.microsoft.com/en-gb/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2](https://docs.microsoft.com/en-gb/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2). I think Kestrel's stdout is piped to syslog by supervisord. So as @tmds said, changing the format on Linux/*nix to a syslog compatible format should do the trick.   Hopefully, it's simple as it sounds 🙂  

Thanks for your detailed comment @tmds 👍

**Comment by anurse** [comment]
All sounds good to me! @tmds IIRC you're looking at this as part of the systemd stuff you talked about with @glennc and me, right?

**Comment by anurse** [comment]
@davidfowl you've talked about wanting to do better an API reviewing. Want to take a quick look at the [proposal here](https://github.com/aspnet/Extensions/issues/647#issuecomment-496573644)?

**Comment by tmds** [comment]
@anurse yes, that's me.

> We use supervisord to monitor the Kestrel processes 

@ATLSAPI from earlier comments I thought you were using systemd? Why supervisord? It will indeed pipe stdout to syslog, but I doubt it supports parsing the priority like systemd does.

**Comment by ATLSAPI** [comment]
> @ATLSAPI from earlier comments I thought you were using systemd? Why supervisord? It will indeed pipe stdout to syslog, but I doubt it supports parsing the priority like systemd does.

Apologies @tmds, that was a mistake. You are right, we use systemd now and this issue definitely happened with systemd. I think we may have briefly used supervisord at the start cos we were on Ubuntu 14.04 at the time, but we're on 18.02 now so we good :+1:

**Comment by BrennanConroy** [comment]
Done via https://github.com/aspnet/Extensions/pull/1777
