### ISSUE TITLE
ConfigureLogging overloading causes VS intellisense to behave badly

### ISSUE THREAD

**Issue by rynowak** [aspnet/Extensions#665]
These are the methods as they are defined today 
```
        public static IWebHostBuilder ConfigureLogging(this IWebHostBuilder hostBuilder, Action<ILoggingBuilder> configureLogging);

        public static IWebHostBuilder ConfigureLogging(this IWebHostBuilder hostBuilder, Action<WebHostBuilderContext, ILoggingBuilder> configureLogging);
```

Try this out, start typing out something like
```
WebHost.CreateDefaultBuilder(args) .ConfigureLogging(b => 
{
    b.    
});
```

The completions after the `b.` are for the `Action<WebHostBuilderContext, ILoggingBuilder>` overload even though we only have one parameter. Basically type inference for the lambda won't do the right thing unless we have exactly correct code inside the lambda.

Since so much of the `ILoggingBuilder` API is extensions, this is a royal pain since intellisense won't show you what's going on.

My guess is that `UseDefaultServiceProvider` also behaves similarly.

**Comment by muratg** [comment]
Not sure if there's any work here. Please reopen if you disagree.

**Comment by cathalnoonan** [comment]
This seems to be related to Visual Studio rather than being an issue for this library...

It seems the type of the arguments are not correctly recognized within the delegate; so following the earlier code sample:
``` csharp
WebHost.CreateDefaultBuilder(args) .ConfigureLogging(b => 
{
    b.            // Intellisense is not working as intended
});
```
A workaround to the intellisense issue is to create a new variable equal to the argument you're looking for that is passed to delegate:
``` csharp
WebHost.CreateDefaultBuilder(args) .ConfigureLogging(b => 
{
    var _b = b;   // VAR's type is inferred correctly
    _b.           // Intellisense is working as intended
});
```
Admittedly, it's a hack rather than a solution - but since the reference type variables are pointing to the same object, it seems this isn't really harming your code

The next person to see this code might just think you're crazy though
