### ISSUE TITLE
Consider publishing Microsoft.Extensions.Logging.Testing to nuget.org

### ISSUE THREAD

**Issue by npnelson** [aspnet/Extensions#672]
Many of my tests make use of the NullLogger defined in:

https://github.com/aspnet/Logging/tree/dev/src/Microsoft.Extensions.Logging.Testing

As far as I can tell, this package isn't published to nuget.org, so I find myself cutting and pasting it and then possibly updating it with every AspNetCore release.

**Comment by muratg** [comment]
We won't be publishing this package.

**Comment by crupest** [comment]
After searching for this package on nuget for about several minutes, I finally got here.
I think I really need this package like some of others above.
Though it may look strange to comment in closed thread, I still want to vote on it hoping one day it will be shipped on nuget. 😅

**Comment by maciejw** [comment]
things like xunit itesthelperoutput and microsoft.extensions.logging integration is very useful... maybe you reconsider... :) 

support on some parts should not be difficult, remember also, you can tag something #need help :)

**Comment by muratg** [comment]
cc @anurse

**Comment by anurse** [comment]
We're not really in a position to support those as "official products", which is why we don't publish them to NuGet. You're always welcome to take the code and clone it (under the, quite permissive, terms of the license), but publishing it as a library on NuGet means backing it as a full on Microsoft product.

> support on some parts should not be difficult, remember also, you can tag something #need help :)

Everything comes with a cost, even community contributions. We can't rely on community contributions to fix critical issues in our products, or security issues. We certainly *welcome* contributions, but we can't fulfill the support commitment we make to our customers without resources.

Also, these components are tightly coupled in to how we build ASP.NET Core and Extensions. If we release them as NuGet packages we have to treat them like public products and avoid breaking changes. That restricts our ability to add things we need to build ASP.NET Core.

We'll certainly keep evaluating that decision as more input comes in, but right now it doesn't feel like the benefit of this (given that the code is fairly simple, very available, and can be easily copied) is worth the cost in supporting it as a product right now.

I'm glad people are finding these useful outside of our intended scenarios, but I don't expect these to be any more than just internal (open-source!) libraries that we don't ship to NuGet.

**Comment by alefranz** [comment]
FYI as I often use bits of this, I've now packaged it alongside some helpers to simplify the consumption in simple scenarios. If anyone else needs it, it is called [MELT](https://github.com/alefranz/MELT).

I've excluded the xUnit output helper as there is already a package for it.
