### ISSUE TITLE
Improve performance of ActivatorUtilities.CreateInstance

### ISSUE THREAD

**Issue by pakrym** [aspnet/Extensions#693]
Currently, it's 30x slower than invoking factory delegate. 
While it could never reach the performance of invoking the factory delegate there is a lot of possible improvements (especially around allocations) in `ActivatorUtilities.CreateInstance`

**Comment by pakrym** [comment]
@anurse I'm pretty sure #1796 didn't fix all of the allocations.

**Comment by Yves57** [comment]
@pakrym Here is a snapshot of the allocated memory when allocating 10000 objects with `ActivatorUtilities.CreateInstance()` (with the official "2.2.0" DependencyInjection package).
I have crossed out the allocations optimized with the last PR.
It remains:
- ConstructorInfo[] -> I don't see any possible optimization. But I may be wrong.
- ParameterInfo[] -> I don't see any possible optimization. But I may be wrong.
- The `object[]` allocated in the `ConstructorMatcher` constructor. We may imagine reuse the array during the matching loop. But this optimization would be valid only if there is more than two constructors, and if the constructors have same number of parameters (`ConstructorInfo.Invoke()` requests a parameter array of the exact length). So it seems very restrictive.

But there is maybe a more generic but trickier optimization [here](https://github.com/dotnet/coreclr/blob/25878db0c11bfb8d52088c75ccfcc13e4c8383f2/src/System.Private.CoreLib/src/System/Reflection/MethodBase.CoreCLR.cs#L108). The method `CheckArguments` is called `RuntimeConstructorInfo.Invoke()` (see the orange rectangle). A copy of the parameters is done because they may be changed by `CheckValue()`. But [`CheckValue()`](https://github.com/dotnet/coreclr/blob/a64cb0a41a4ebeb4a61b8b0f1f2eeeff8dd539c9/src/System.Private.CoreLib/src/System/RtType.cs#L3714) seems to returns the object as-is in the *normal* case. So we could imagine a lazy allocation of the `copyOfParameters` array only if the parameter is changed by `CheckValue()`.
The advantage is that *any* object construction (and maybe other reflection calls) could benefit of this optimization. But the optimization seems too big to be correct. I suppose that something is wrong in my analysis :-).

![image](https://user-images.githubusercontent.com/11701094/59097383-b11c7580-891d-11e9-8802-4da4416b3549.png)

**Comment by pakrym** [comment]
@Yves57 thank you for detailed analysis, I think you've done all the appropriate optimizations. We can keep the issue closed.

**Comment by Yves57** [comment]
@pakrym Do you think it makes sense to open an issue in CoreClr about the "lazy allocation" (last point of my previous comment)?

**Comment by pakrym** [comment]
@Yves57, yeah, do it.

**Comment by anurse** [comment]
TIL that it's the person who merges the PR that gets credit for closing linked issues ;P.

Sounds good, thanks for filing that issue @Yves57 !
