### ISSUE TITLE
Add support for running Generic Host based applications as a Windows Service

### ISSUE THREAD

**Issue by feco93** [aspnet/Extensions#809]
Currently RunAsService depends on IWebHost.  It should be depend on IHost interface, because it would be great if anyone could write windows service without the HTTP infrastructure.

There is an SO post, which about this feature request: 
https://stackoverflow.com/questions/50848141/netcore-2-1-generic-host-as-a-service

**Comment by Tratcher** [comment]
Try to build in all the workarounds from https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2
- current directory
- only register the service lifetime if in a service, otherwise console
- AddEventLog?

**Comment by Tratcher** [comment]
@davidfowl AddEventLog turns out to be very useful, but it's also awkward to include by default because you can only configure it in the AddEventLog call. How about we add that to the docs instead?

The ContentRootPath workaroud isn't required, we already set it in generic host.
`ContentRootPath = ResolveContentRootPath(_hostConfiguration[HostDefaults.ContentRootKey], AppContext.BaseDirectory),`
We don't want to set CurrentDirectory, right?

Detecting if we're in a service turns out to be quite difficult...

**Comment by davidfowl** [comment]
We can consider turning this on by default in CreateDefaultBuilder if running on windows and for errors only (it's useful for ASP.NET Core applications as well).

**Comment by davidfowl** [comment]
> The ContentRootPath workaroud isn't required, we already set it in generic host.
ContentRootPath = ResolveContentRootPath(_hostConfiguration[HostDefaults.ContentRootKey], AppContext.BaseDirectory),
We don't want to set CurrentDirectory, right?

No, I don't think we want to do that (even though we're doing it in the IIS case). We can doc it though.

**Comment by stevejgordon** [comment]
@davidfowl @Tratcher - Just FYI, my blog post on achieving this (sort of) with the code from Microsoft.AspNetCore.Hosting.WindowsServices is one of the highest viewed posts monthly at the moment, so it would suggest quite a high customer interest in this feature. Not that I use it personally as I'm all about the Linux containers; I'm happy to update the information or add a new post once something baked in is available in the previews.
