### ISSUE TITLE
ConfigurationProviders leak memory

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Extensions#861]
```C#
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;

namespace WebApplication45
{
    public class Program
    {
        public static async Task Main(string[] args)
        {
            Console.WriteLine("STARTING");
            Console.ReadLine();
            CreateConfig();
            Console.WriteLine("DONE");
            Console.ReadLine();
        }

        private static void CreateConfig()
        {
            for (int i = 0; i < 1000; i++)
            {
                var config = new ConfigurationBuilder()
                               .SetBasePath(Environment.CurrentDirectory)
                               .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                               .Build();
            }
        }
    }
}
```

This roots tons of objects because of https://github.com/aspnet/Extensions/issues/786 they can't be cleaned up.

![image](https://user-images.githubusercontent.com/95136/50367962-d3216780-0538-11e9-8e15-e53e489b7455.png)

**Comment by poke** [comment]
Just wondering if this would be the way we would solve this:

- Make `ConfigurationRoot` disposable
- Dispose all disposable providers when disposing the `ConfigurationRoot`
- In `WebHost`, dispose of the `ConfigurationRoot` when the web host gets disposed

If that’s correct, I would be interested to pick this up.

Since the configuration is also used in the `WebHostBuilder` I assume that we would need to add a way to dispose of the configuration root there as well (making the builder disposable)?

**Comment by davidfowl** [comment]
> Make ConfigurationRoot disposable

Yes.

> Dispose all disposable providers when disposing the ConfigurationRoot

Yes

> In WebHost, dispose of the ConfigurationRoot when the web host gets disposed

This should happen for free since the ConfigurationRoot  is in the container.

**Comment by poke** [comment]
@davidfowl
> This should happen for free since the ConfigurationRoot is in the container.

But doesn’t aspnet/DependencyInjection#462 prevent the configuration root from getting disposed since it is being registered [as an instance](https://github.com/aspnet/AspNetCore/blob/v2.2.1/src/Hosting/Hosting/src/WebHostBuilder.cs#L282)?

**Comment by davidfowl** [comment]
Ah, yes you're right! We need to do the same for the hosting environment as well.

**Comment by poke** [comment]
You mean make [HostingEnvironment](https://github.com/aspnet/AspNetCore/blob/v2.2.1/src/Hosting/Hosting/src/Internal/HostingEnvironment.cs) disposable and dispose the two file providers? Or maybe dispose of those manually (maybe through an extension method) since the hosting environment itself is just a POCO while [an extension method](https://github.com/aspnet/AspNetCore/blob/v2.2.1/src/Hosting/Hosting/src/Internal/HostingEnvironmentExtensions.cs) does the actual work?

Also, since we agree to dispose the configuration root manually now, what is your opinion on disposing the original configuration root inside the web host builder? Looking at how it is used (and how the web host builder just allows to be built once), I guess we could also dispose the config after the web host is being built and forward `_config` to the `_context.Configuration` instead (which is the host’s config)?

**Comment by davidfowl** [comment]
Fixed

**Comment by poke** [comment]
@davidfowl We still need the work on the AspNetCore side though. I'm working on that (currently struggling with getting the repo to build).

**Comment by davidfowl** [comment]
@poke We actually need it in 2 places. It needs to go into the generic host (that's the default in 3.0) and in the WebHost for compat.
