### ISSUE TITLE
ObjectPool should support Dispose

### ISSUE THREAD

**Issue by rynowak** [aspnet/Extensions#973]
Currently the ObjectPool does not implement `IDisposable` and thus does not dispose objects managed by the pool.

We didn't do this in the past, because we don't use the ObjectPool with Disposables, but it would be a blocker for anyone external who wanted to.

**Comment by gfoidl** [comment]
I've this should be implemented, I'm happy to do this :smile:

**Comment by gfoidl** [comment]
You mean https://github.com/aspnet/Extensions/issues/296 (moved to https://github.com/aspnet/AspNetCore/issues/2359)?

What should happen when the pool is disposed and `Get` / `Return` is called after? Throw a `ObjectDisposedException` or just create new fresh elements?

Maybe it would be better to have a `DisposableObjectPool` (that derives from `DefaultObjectPool`), to keep the default one fast, and the new one correct at handling the disposables.
Alternatively the pool could switch its internal working based on `T`.

**Comment by rynowak** [comment]
re: get/return after dispose - I would expect Get` to throw ODE and Return to dispose the item that was put in. It's a lot friendlier to allow you to return when stuff is shutting down because there might be a race condition, or other services might return items as part of their dispose method.  I'm open to other ideas about this but it's definitely a goal of mine to avoid making people reason about the order in which services will be disposed during shutdown.

I think a separate `DisposeableObjectPool` is a great idea, it also doesn't have to derive if it makes more sense. I'd suggest making the `DefaultObjectPoolProvider` smart enough to create the correct pool based on the type you provide. We also might want a static `ObjectPool.Create<T>` with the same smarts as the recommended way to create a pool without using DI. 

/cc @davidfowl @glennc - in case thoughts

**Comment by huoyaoyuan** [comment]
I'm finding a pool suitable for unmanaged resource wrappers. These object should **not** get `Dispose` called when returned, because unmanaged resource are reused. Exposing the disposal of object pool itself is critical, to dispose unmanaged resources correctly.

Seems `DisposableObjectPool` does follow my requirements after reading the code. Better to do some documentation for this.

**Comment by gfoidl** [comment]
@anurse first this issue should be closed as it got resolved by https://github.com/aspnet/Extensions/pull/977?

> Better to do some documentation for this.

@huoyaoyuan is right. But I'm not the best at writing documentations, but I'm happy to help out (as I implemented this disposable-pool).

**Comment by anurse** [comment]
@gfoidl yep. Looks like this is done.

> Better to do some documentation for this.

Is documentation enough here? If the object implements IDisposable, it seems it will use the DisposableObjectPool, there isn't really a way to prevent that. Or is the suggestion to document that if you create an ObjectPool<T> with a disposable T it will be disposed? If so, XML docs are probably the best solution here since I don't know that we have a narrative doc for this.

**Comment by rynowak** [comment]
See comment here: https://github.com/aspnet/Extensions/blob/master/src/ObjectPool/src/DisposableObjectPool.cs#L41

The pool will dispose an object that it "forgets". 

Our pool implementation is based on retaining some amount of items when they are returned to the pool. You can always **lease** as many objects as you want and return them - we'll only keep a fixed number in the pool.

If the pool size is 10, and you lease 15 objects and then return them, we will keep 10, and the dispose 5.
